"""Static Next.js 14 (App Router) + Tailwind scaffold files."""

from __future__ import annotations

from pathlib import Path


def default_files() -> dict[str, str]:
    """Relative path -> file contents for a minimal buildable Next.js app."""
    return {
        "package.json": """{
  "name": "sandbox-app",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "dev": "npx --no-install next dev",
    "build": "npx --no-install next build",
    "start": "npx --no-install next start",
    "lint": "npx --no-install next lint"
  },
  "dependencies": {
    "next": "14.2.18",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/node": "^20.14.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.2.18",
    "postcss": "^8.4.39",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.5.0"
  }
}
""",
        "tsconfig.json": """{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
""",
        "next-env.d.ts": """/// <reference types="next" />
/// <reference types="next/image-types/global" />
""",
        "next.config.mjs": """/** @type {import('next').NextConfig} */
const nextConfig = {};
export default nextConfig;
""",
        "postcss.config.mjs": """const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
export default config;
""",
        "tailwind.config.ts": """import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: { extend: {} },
  plugins: [],
};
export default config;
""",
        ".eslintrc.json": """{
  "extends": "next/core-web-vitals"
}
""",
        "app/globals.css": """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground: #0a0a0a;
  --background: #fafafa;
}

body {
  color: var(--foreground);
  background: var(--background);
}
""",
        "app/layout.tsx": """import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Sandbox App",
  description: "Generated by nextjs-sandbox-agent",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">{children}</body>
    </html>
  );
}
""",
        "app/page.tsx": """export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <p className="text-lg text-neutral-600">Replace this page via generation.</p>
    </main>
  );
}
""",
        "components/Button.tsx": """import type { ButtonHTMLAttributes } from "react";

export function Button({
  className = "",
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      className={
        "inline-flex items-center justify-center rounded-md bg-neutral-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-neutral-800 disabled:opacity-50 " +
        className
      }
      {...props}
    />
  );
}
""",
        "components/Card.tsx": """import type { HTMLAttributes } from "react";

export function Card({
  className = "",
  ...props
}: HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={
        "rounded-xl border border-neutral-200 bg-white p-6 shadow-sm " +
        className
      }
      {...props}
    />
  );
}
""",
        ".gitignore": """node_modules/
.next/
out/
.env
.env*.local
.vercel
*.log
.DS_Store
.agent_build_attempts
.agent_github_device.json
.agent_github_user_token
""",
    }


def write_workspace(root: Path, page_tsx: str | None = None) -> None:
    """Create all scaffold files under root."""
    files = default_files()
    if page_tsx is not None:
        files = {**files, "app/page.tsx": page_tsx}
    for rel, content in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
